on: [push]
 
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run selenium E2E tests
    steps:
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
 
    - uses: actions/checkout@v1
    - run: npm ci  
 
    - name: Run end to end tests
      run: npm run selenium-e2e-test